version: '3.1'
services:
  league_api:
    build: ./lig-api
    ports:
     - "3000:3000"
    depends_on:
     - redis
     - mariadb
     - rabbitmq
    environment:
     - REDIS_HOST=redis
     - MYSQL_HOST=mariadb
     - RABBITMQ_HOST=rabbitmq
  league_service:
    build: ./lig-service
    depends_on:
     - mariadb
     - rabbitmq
    environment:
     - MYSQL_HOST=mariadb
     - RABBITMQ_HOST=rabbitmq
  mariadb:
    image: mariadb:10.5
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./app/mariadb-data:/var/lib/mysql" 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leaguedb
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: password

